#!/bin/sh
# From <https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html>
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
# Note that `--recurse-submodules` may make the tags file very large.
git ls-files --recurse-submodules | ctags --tag-relative -L - -f"$$.tags" --languages=-javascript,sql
mv "$$.tags" ".tags"
