font:
  size: 14.0
  normal:
    # family: DejaVu Sans Mono
    family: DM Mono

# TokyoNight Moon
colors:
  # Default colors
  primary:
    background: '0x222436'
    foreground: '0xc8d3f5'

  # Normal colors
  normal:
    black:   '0x1b1d2b'
    red:     '0xff757f'
    green:   '0xc3e88d'
    yellow:  '0xffc777'
    blue:    '0x82aaff'
    magenta: '0xc099ff'
    cyan:    '0x86e1fc'
    white:   '0x828bb8'

  # Bright colors
  bright:
    black:   '0x444a73'
    red:     '0xff757f'
    green:   '0xc3e88d'
    yellow:  '0xffc777'
    blue:    '0x82aaff'
    magenta: '0xc099ff'
    cyan:    '0x86e1fc'
    white:   '0xc8d3f5'

  indexed_colors:
    - { index: 16, color: '0xff966c' }
    - { index: 17, color: '0xc53b53' }

# <https://github.com/alacritty/alacritty/wiki/Color-schemes>
# Colors (Solarized Dark)
# colors:
#   # Default colors
#   primary:
#     background: '#002b36' # base03
#     foreground: '#839496' # base0
#
#   # Cursor colors
#   cursor:
#     text:   '#002b36' # base03
#     cursor: '#839496' # base0
#
#   # Normal colors
#   normal:
#     black:   '#073642' # base02
#     red:     '#dc322f' # red
#     green:   '#859900' # green
#     yellow:  '#b58900' # yellow
#     blue:    '#268bd2' # blue
#     magenta: '#d33682' # magenta
#     cyan:    '#2aa198' # cyan
#     white:   '#eee8d5' # base2
#
#   # Bright colors
#   bright:
#     black:   '#586e75' # base01
#     red:     '#cb4b16' # orange
#     green:   '#586e75' # base01
#     yellow:  '#657b83' # base00
#     blue:    '#839496' # base0
#     magenta: '#6c71c4' # violet
#     cyan:    '#93a1a1' # base1
#     white:   '#fdf6e3' # base3
